### ISSUE TITLE
Debug the scheduler function

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#11]
There is some error in the scheduler func, that needs to be debugged

**Comment by RishikaGhosh** [comment]
Where is this function located? Is this the one in the /include/functions.h file?

**Comment by RounakNeogy** [comment]
I want to contribute in this project

**Comment by RounakNeogy** [comment]
> Where is this function located? Is this the one in the /include/functions.h file?

yes i guess

**Comment by RishikaGhosh** [comment]
I want to contribute to this issue too

**Comment by rhack1221** [comment]
Hey!! I want to contribute to this code

**Comment by sb2356-iiitr** [comment]
Hi! I would like to contribute to the code.

**Comment by sagnik1511** [comment]
Hi ! want to contribute in issue #11

**Comment by Dutta-SD** [comment]
Hello @anushka23g . I am Sandip. Is this issue assigned to anyone? Otherwise I would like to work on it.

**Comment by anushka23g** [comment]
Open to all
