### ISSUE TITLE
Add more content to readme

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#13]
go through the code and understand the project and add more meaningful content to the readme.

**Comment by pawki07** [comment]
I would like to contribute to this issue. Please assign it to me.

**Comment by sb2356-iiitr** [comment]
I would like to contribute to the project.

**Comment by anushka23g** [comment]
assigned to @pawki07

**Comment by pawki07** [comment]
Okay, I have started working on it.
