### ISSUE TITLE
Update License as MIT License

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#18]
Include MIT license.

**Comment by sagnik1511** [comment]
I want to book this issue

**Comment by soumita1234** [comment]
I would like to do this..could you please assign me

**Comment by sagnik1511** [comment]
> I would like to do this..could you please assign me

I guess coding phase will start after 21st.Then this will be decided.

**Comment by sagnik1511** [comment]
I want to resolve this issue. Please assign me.
I have updated a MIT license in my own repo

https://github.com/sagnik1511/Tabular-Playground-Series-Competition

**Comment by anushka23g** [comment]
Assigned to @sagnik1511

**Comment by sagnik1511** [comment]
![](https://cdn.discordapp.com/attachments/800605546754342923/801660405834580038/Screenshot_417.png)
 I've updated the MIT License .. Can I call for PR for issue #18 ?

**Comment by anushka23g** [comment]
merged
