### ISSUE TITLE
Create Code of Conduct. md

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#21]

**Comment by sagnik1511** [comment]
I want to book this Issue. I'll solve it

**Comment by djm-1** [comment]
I would like to do this. Please assign me 😊

**Comment by pawki07** [comment]
Can I work on this issue. Please assign it to me.

**Comment by anushka23g** [comment]
Assigned to @djm-1

**Comment by snkt0809** [comment]
I wanna contribute.

**Comment by djm-1** [comment]
> 
> 
> Assigned to @djm-1

I have created PR https://github.com/anushka23g/Learning-Made-Easy/pull/25.

**Comment by anushka23g** [comment]
merged

**Comment by sb2356-iiitr** [comment]
@all-contributors please add @djm-1 for documentation

**Comment by sb2356-iiitr** [comment]
@all-contributors please add @djm-1 for documentation
