### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by kiruba-r11** [anushka23g/Learning-Made-Easy#38]
There is a small typo in `Clone it` and `Sync it` section under `Steps to follow`. 
They are listed below

This will change directory to a folder `Algo_Ds_Notes` (should be `Learning-Made-Easy`)
$ cd Learning-Made-Easy

Push changes to your forked `Algo_Ds_Notes` (should be `Learning-Made-Easy`) repo
$ git push origin master

**Comment by kiruba-r11** [comment]
Can i work on it?

**Comment by anushka23g** [comment]
Yeah
