### ISSUE TITLE
Beautify the Readme.md

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#4]
We need a more attractive version of the current readme file.

**Comment by shubhigupta991** [comment]
I want to work on this issue. Please assign it to me.

**Comment by anushka23g** [comment]
yeah sure, go ahead!

**Comment by shivshankar9** [comment]
I want to work on this..

**Comment by anushka23g** [comment]
yeah sure, go ahead!

**Comment by aditisneh** [comment]
I would like to work on this.

**Comment by anushka23g** [comment]
yeah sure, go ahead!

**Comment by Dutta-SD** [comment]
The README looks great! Can I add a section on how to install and run the task (git cloning, running, compiling etc?)

**Comment by anushka23g** [comment]
assigned to @Dutta-SD
