### ISSUE TITLE
Making it user friendly

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#5]
try to make it more user friendly by adding GUI or other support

**Comment by vaishnavirshah** [comment]
Hi, so I would like to beautify the code for the terminal itself before moving onto adding a GUI.

**Comment by anushka23g** [comment]
yeah sure, go ahead!

**Comment by vaishnavirshah** [comment]
I have made a PR, now should I create an issue for GUI also?

**Comment by anushka23g** [comment]
yes please do

**Comment by sagnik1511** [comment]
Is this issue open ? Then I'll be happy to contribute to issue #5. Please assign if it is still open.  :)

**Comment by anushka23g** [comment]
assigned to @sagnik1511

**Comment by draveshjaluka** [comment]
i have already made this code more user friendly in the terminal window, if you could me about the GUI i would like to work on that as well

**Comment by anushka23g** [comment]
yes go ahead
