### ISSUE TITLE
Work on wiki

### ISSUE THREAD

**Issue by anushka23g** [anushka23g/Learning-Made-Easy#7]
Define a roadmap for the project

**Comment by samflab** [comment]
Hi, can you tell more about this issue so that it becomes easier to work on.
Thanks

**Comment by anushka23g** [comment]
yeah sure, wikis are basically for documenting your project just like the readme file. But the difference is that they are more comprehensive than the readme file and present in-depth information about the project.

**Comment by shagun25** [comment]
can i take this issue?
would like to work on this.
@anushka23g

**Comment by anushka23g** [comment]
Assigned to @shagun25

**Comment by shagun25** [comment]
Have a look on this [https://whimsical.com/roadmap-learning-made-easy-TjfbrRRMXsVDT41i5E4PCr](url)
suggest changes if required.....
![roadmap(learning made easy)](https://user-images.githubusercontent.com/63994999/105625981-1571ad00-5e53-11eb-9a04-8b7db17db2e2.png)

@anushka23g

**Comment by anushka23g** [comment]
seems to be good

**Comment by shagun25** [comment]
great then . so we can close the issue @anushka23g

**Comment by anushka23g** [comment]
Make a section for this in readme and add it there, then we can close it.
